name: lab5 tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Check current location
      run: ls -la
    - name: Check java version
      run: java -version
    - name: MVN ver
      run: mvn --version
    - name: Run tests with Maven
      run: mvn clean test --file 2/pom.xml
